### ISSUE TITLE
Not able to apply options from mozconfig

### ISSUE THREAD

**Issue by HarvHouHacker** [JOYProjects/Light-Web-Browser#12]
After adding options in a new mozconfig file in the root directory, I ran `./mach configure` and it succeeded. I then ran `./mach build` and got this error:
```
 0:10.43 Traceback (most recent call last):
 0:10.44   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
 0:10.44     "__main__", fname, loader, pkg_name)
 0:10.44   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
 0:10.44     exec code in run_globals
 0:10.45   File "$HOME_DIR$/firefox-53.0.3/python/mozbuild/mozbuild/action/webidl.py", line 19, in <module>
 0:10.45     sys.exit(main(sys.argv[1:]))
 0:10.45   File "$HOME_DIR$/firefox-53.0.3/python/mozbuild/mozbuild/action/webidl.py", line 15, in main
 0:10.45     manager.generate_build_files()
 0:10.45   File "$HOME_DIR$/firefox-53.0.3/dom/bindings/mozwebidlcodegen/__init__.py", line 248, in generate_build_files
 0:10.45     self._parse_webidl()
 0:10.45   File "$HOME_DIR$/firefox-53.0.3/dom/bindings/mozwebidlcodegen/__init__.py", line 335, in _parse_webidl
 0:10.45     self._parser_results = parser.finish()
 0:10.45   File "$HOME_DIR$/firefox-53.0.3/dom/bindings/parser/WebIDL.py", line 6862, in finish
 0:10.45     production.finish(self.globalScope())
 0:10.46   File "$HOME_DIR$/firefox-53.0.3/dom/bindings/parser/WebIDL.py", line 840, in finish
 0:10.46     self.parent.finish(scope)
 0:10.46   File "$HOME_DIR$/firefox-53.0.3/dom/bindings/parser/WebIDL.py", line 929, in finish
 0:10.46     member.finish(scope)
 0:10.46   File "$HOME_DIR$/firefox-53.0.3/dom/bindings/parser/WebIDL.py", line 3978, in finish
 0:10.46     t = self.type.complete(scope)
 0:10.46   File "$HOME_DIR$/firefox-53.0.3/dom/bindings/parser/WebIDL.py", line 2320, in complete
 0:10.46     self.inner = self.inner.complete(scope)
 0:10.47   File "$HOME_DIR$/firefox-53.0.3/dom/bindings/parser/WebIDL.py", line 2170, in complete
 0:10.47     [self.location])
 0:10.48 WebIDL.WebIDLError: error: Unresolved type '<unresolved scope>::AccessibleNode'., $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/bindings/Node.webidl line 112:21
 0:10.48   readonly attribute AccessibleNode? accessibleNode;
 0:10.48                      ^
```
Here are the options I allowed in the mozconfig:
```
ac_add_options --enable-application=browser
mk_add_options MOZ_MAKE_FLAGS=-j2
export MOZ_PSEUDO_DERECURSE=no-pymake 
ac_add_options --with-branding=browser/branding/light
ac_add_options --disable-directshow
ac_add_options --disable-updater
ac_add_options --disable-maintenance-service
ac_add_options --disable-crashreporter
ac_add_options --disable-dbm
ac_add_options --disable-webrtc
ac_add_options --disable-parental-controls
ac_add_options --disable-gamepad
ac_add_options --disable-necko-wifi
ac_add_options --without-intl-api
ac_add_options --disable-accessibility
ac_add_options --disable-safe-browsing
ac_add_options --disable-printing
ac_add_options --disable-shared-js
ac_add_options --disable-webspeech
ac_add_options --disable-debug-symbols
```

**Comment by HarvHouHacker** [comment]
Source is compiling. Commented out `ac_add_options --disable-accessibility`; had to also comment out `ac_add_options --disable-webspeech`. It's building now. 😃

**Comment by HarvHouHacker** [comment]
Well, this is embarrassing.
```
36:04.71 libnetwerk_cache.a.desc
36:07.08 In file included from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/mozilla/MediaManager.h:8:0,
36:07.08                  from $HOME_DIR$/firefox-53.0.3/dom/media/MediaDeviceInfo.cpp:7,
36:07.08                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:137:
36:07.08 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:229:28: error: reference to ‘ipc’ is ambiguous
36:07.08                       const ipc::PrincipalInfo& aPrincipalInfo,
36:07.08                             ^
36:07.09 In file included from $HOME_DIR$/firefox-53.0.3/netwerk/base/nsTemporaryFileInputStream.h:12:0,
36:07.09                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/mozilla/dom/File.h:26,
36:07.09                  from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.cpp:8,
36:07.09                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:2:
36:07.09 $HOME_DIR$/firefox-53.0.3/ipc/glue/nsIIPCSerializableInputStream.h:16:15: note: candidates are: namespace mozilla::ipc { }
36:07.09  namespace ipc {
36:07.09                ^
36:07.09 In file included from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.h:11:0,
36:07.09                  from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.cpp:7,
36:07.09                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:2:
36:07.10 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/nsTArray.h:55:15: note:                 namespace mozilla::dom::ipc { }
36:07.10  namespace ipc {
36:07.10                ^
36:07.11 In file included from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/mozilla/MediaManager.h:8:0,
36:07.11                  from $HOME_DIR$/firefox-53.0.3/dom/media/MediaDeviceInfo.cpp:7,
36:07.11                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:137:
36:07.11 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:229:46: error: expected unqualified-id before ‘&’ token
36:07.11                       const ipc::PrincipalInfo& aPrincipalInfo,
36:07.11                                               ^
36:07.11 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:229:46: error: expected ‘)’ before ‘&’ token
36:07.12 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:229:46: error: constructors may not be ref-qualified
36:07.12 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:229:46: error: expected ‘;’ at end of member declaration
36:07.12 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:229:48: error: ‘aPrincipalInfo’ does not name a type
36:07.12                       const ipc::PrincipalInfo& aPrincipalInfo,
36:07.12                                                 ^
36:07.13 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:239:5: error: reference to ‘ipc’ is ambiguous
36:07.13      ipc::PrincipalInfo mPrincipalInfo;
36:07.13      ^
36:07.13 In file included from $HOME_DIR$/firefox-53.0.3/netwerk/base/nsTemporaryFileInputStream.h:12:0,
36:07.13                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/mozilla/dom/File.h:26,
36:07.13                  from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.cpp:8,
36:07.13                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:2:
36:07.14 $HOME_DIR$/firefox-53.0.3/ipc/glue/nsIIPCSerializableInputStream.h:16:15: note: candidates are: namespace mozilla::ipc { }
36:07.14  namespace ipc {
36:07.14                ^
36:07.15 In file included from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.h:11:0,
36:07.15                  from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.cpp:7,
36:07.15                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:2:
36:07.15 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/nsTArray.h:55:15: note:                 namespace mozilla::dom::ipc { }
36:07.15  namespace ipc {
36:07.15                ^
36:07.15 In file included from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/mozilla/MediaManager.h:8:0,
36:07.15                  from $HOME_DIR$/firefox-53.0.3/dom/media/MediaDeviceInfo.cpp:7,
36:07.16                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:137:
36:07.16 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:330:35: error: reference to ‘ipc’ is ambiguous
36:07.16                              const ipc::PrincipalInfo& aPrincipalInfo,
36:07.16                                    ^
36:07.16 In file included from $HOME_DIR$/firefox-53.0.3/netwerk/base/nsTemporaryFileInputStream.h:12:0,
36:07.16                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/mozilla/dom/File.h:26,
36:07.16                  from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.cpp:8,
36:07.17                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:2:
36:07.17 $HOME_DIR$/firefox-53.0.3/ipc/glue/nsIIPCSerializableInputStream.h:16:15: note: candidates are: namespace mozilla::ipc { }
36:07.17  namespace ipc {
36:07.18                ^
36:07.18 In file included from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.h:11:0,
36:07.18                  from $HOME_DIR$/firefox-53.0.3/dom/media/EncodedBufferCache.cpp:7,
36:07.18                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:2:
36:07.18 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/nsTArray.h:55:15: note:                 namespace mozilla::dom::ipc { }
36:07.18  namespace ipc {
36:07.18                ^
36:07.18 In file included from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/mozilla/MediaManager.h:8:0,
36:07.18                  from $HOME_DIR$/firefox-53.0.3/dom/media/MediaDeviceInfo.cpp:7,
36:07.19                  from $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp:137:
36:07.19 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:330:53: error: expected unqualified-id before ‘&’ token
36:07.19                              const ipc::PrincipalInfo& aPrincipalInfo,
36:07.19                                                      ^
36:07.20 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:330:53: error: expected ‘)’ before ‘&’ token
36:07.20 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:330:53: error: expected ‘;’ at end of member declaration
36:07.20 $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/MediaEngine.h:330:55: error: ‘aPrincipalInfo’ does not name a type
36:07.20                              const ipc::PrincipalInfo& aPrincipalInfo,
36:07.20                                                        ^
36:14.66 
36:14.66 In the directory  $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media
36:14.66 The following command failed to execute properly:
36:14.66 /usr/bin/g++ -std=gnu++11 -o Unified_cpp_dom_media1.o -c -I$HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/stl_wrappers -I$HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/system_wrappers -include $HOME_DIR$/firefox-53.0.3/config/gcc_hidden.h -DNDEBUG=1 -DTRIMMED=1 -DMOZILLA_INTERNAL_API -DWEBRTC_POSIX -DOS_POSIX=1 -DOS_LINUX=1 -DSTATIC_EXPORTABLE_JS_API -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -I$HOME_DIR$/firefox-53.0.3/dom/media -I$HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media -I$HOME_DIR$/firefox-53.0.3/caps -I$HOME_DIR$/firefox-53.0.3/dom/base -I$HOME_DIR$/firefox-53.0.3/layout/generic -I$HOME_DIR$/firefox-53.0.3/layout/xul -I$HOME_DIR$/firefox-53.0.3/netwerk/base -I$HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/ipc/ipdl/_ipdlheaders -I$HOME_DIR$/firefox-53.0.3/ipc/chromium/src -I$HOME_DIR$/firefox-53.0.3/ipc/glue -I$HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include -I$HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/nspr -I$HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dist/include/nss -fPIC -DMOZILLA_CLIENT -include $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/mozilla-config.h -MD -MP -MF .deps/Unified_cpp_dom_media1.o.pp -Wall -Wc++11-compat -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings -Wno-invalid-offsetof -Wc++14-compat -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -fno-lifetime-dse -fno-exceptions -fno-strict-aliasing -fno-rtti -fno-exceptions -fno-math-errno -pthread -pipe -freorder-blocks -Os -fomit-frame-pointer -Wno-error=attributes -Wno-error=shadow -fdiagnostics-color $HOME_DIR$/firefox-53.0.3/obj-x86_64-pc-linux-gnu/dom/media/Unified_cpp_dom_media1.cpp
36:14.67 $HOME_DIR$/firefox-53.0.3/config/rules.mk:993: recipe for target 'Unified_cpp_dom_media1.o' failed
36:14.67 make[5]: *** [Unified_cpp_dom_media1.o] Error 1
36:14.67 $HOME_DIR$/firefox-53.0.3/config/recurse.mk:71: recipe for target 'dom/media/target' failed
36:14.67 make[4]: *** [dom/media/target] Error 2
36:14.67 make[4]: *** Waiting for unfinished jobs....
37:16.01 libdom_canvas.a.desc
37:16.12 $HOME_DIR$/firefox-53.0.3/config/recurse.mk:32: recipe for target 'compile' failed
37:16.12 make[3]: *** [compile] Error 2
37:16.12 $HOME_DIR$/firefox-53.0.3/config/rules.mk:522: recipe for target 'default' failed
37:16.13 make[2]: *** [default] Error 2
37:16.13 $HOME_DIR$/firefox-53.0.3/client.mk:419: recipe for target 'realbuild' failed
37:16.13 make[1]: *** [realbuild] Error 2
37:16.13 client.mk:170: recipe for target 'build' failed
37:16.13 make: *** [build] Error 2
37:16.13 0 compiler warnings present.
37:16.69 /usr/bin/notify-send --app-name=Mozilla Build System Mozilla Build System Build failed
```
What could have possibly gone wrong this time?!?

**Comment by HarvHouHacker** [comment]
Removed mozconfig in root directory, ran `./mach configure` and `./mach build` again. Took over an hour and a half, but it finished with no errors and runs. Something's wrong with my mozconfig options. Need a little help from @mozilla.

**Comment by HarvHouHacker** [comment]
I can fix it - closing yet another useless issue.
